config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      resources :comments, only: [:new]
    end
  end
  resources :comments, only: [:create]

  post "/upvote", to: "votes#upvote"
  post "/downvote", to: "votes#downvote"

  root to: "subs#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, :post_id, :content, presence: true

  belongs_to :author,
  foreign_key: :user_id,
  class_name: :User

  belongs_to :post

  has_many :votes, as: :votable

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  def self.scores
    Vote
      .where(votable_type: "Comment")
      .group(:votable_id)
      .sum(:value)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :check_logged_in

  def new
    @comment = Comment.new
    @post = Post.find_by_id(params[:id])
    @parent_comment_id = params[:parent_comment_id]

  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      fail
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  private

  def check_logged_in
    unless current_user
      flash[:errors] = ["You must log in before commenting!"]
      redirect_to new_session_url
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div>
  <%= comment.author.user_name %></br>
  Score: <%= @comment_scores[comment.id] || 0  %>
  <%= render "votes/vote_buttons", votable_id: comment.id, votable_type: "Comment" %>
  <p>
    <%= comment.content %>
  </p>

  <%= link_to "reply", new_comment_url(parent_comment_id: comment.id)%>

  <ul>
    <% @comments_by_parent_id[comment.id].each do |child| %>
      <li> <%= render "comments/comment", comment: child %> </li>
    <% end %>
  </ul>

</div>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>", method="post" >

  <%= auth_token %>

  <label id="comment_content"> Content </label>
    <textarea
      id="comment_content"
      name="comment[content]"> <%= @comment.content %> </textarea>

  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @parent_comment_id %>">
  <input type="submit">

</form>

app/views/comments/new.html.erb
<h1> Create a comment </h1>

<%= render "form" %>