config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      resources :comments, only: [:new]
    end
  end
  resources :comments, only: [:create]

  post "/upvote", to: "votes#upvote"
  post "/downvote", to: "votes#downvote"

  root to: "subs#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  before_validation :ensure_session_token

  has_many :votes 

  validates :user_name, :session_token, :password_digest, presence: true
  validates :password, length: { in: 6..20, allow_nil: true }

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Sub

  has_many :comments,
    foreign_key: :user_id,
    class_name: :Comment

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(32)
  end

  def reset_session!
    token = generate_session_token
    self.session_token = token
    self.save
    token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    user unless user.nil? || !user.is_password?(password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form action="<%=action %>", method="post" >
  <%= auth_token %>

  <label id="user_name"> Username </label>
    <input
      id="user_name"
      name="user[user_name]"
      value="username"
     >

  <label id="user_password"> Password </label>
    <input
      id="user_password"
      name="user[password]"
      value="password"
      type="password"
     >

    <input type="Submit" value="<%= submit_msg %>">

</form>

app/views/users/new.html.erb
<h1> JOIN US </h1>

<%= render "form", action: users_url, submit_msg: "Sign up!"%>