config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      resources :comments, only: [:new]
    end
  end
  resources :comments, only: [:create]

  post "/upvote", to: "votes#upvote"
  post "/downvote", to: "votes#downvote"

  root to: "subs#index"
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :user_id, :title, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User,
    dependent: :destroy

  has_many :post_subs, inverse_of: :sub
  has_many :posts, through: :post_subs, source: :post

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :check_sub_owner, only: [:update, :edit]
  before_action :check_logged_in, only: [:create, :new]

  def check_logged_in
    unless current_user
      flash[:errors] = ["You must log in before creating a sub!"]
      redirect_to new_session_url
    end
  end


  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by_id(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by_id(params[:id])
    @sub.user_id = current_user.id

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.includes(:posts).find_by_id(params[:id])
    render :show
  end

  private

  def check_sub_owner
    @sub = Sub.find_by_id(params[:id])
    unless @sub.user_id == current_user.id
      flash[:errors] = ["You cannot edit a sub that does not belong to you :("]
      redirect_to sub_url(@sub)
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :user_id)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form action="<%=action %>", method="post" >
  <input type="hidden" name="_method" value="<%= method %>" />
  <%= auth_token %>

  <label id="sub_title"> Title: </label>
    <input
      id="sub_title"
      name="sub[title]"
      value="<%= @sub.title %>"
     />

  <label id="sub_description"> Description </label>
    <textarea
      id="sub_description"
      name="sub[description]"> <%= @sub.description %> </textarea>

  <input type="submit">

</form>

app/views/subs/edit.html.erb
<h1> Modify a sub </h1>
<%= render "form", action: sub_url(@sub), method: "patch" %>

app/views/subs/index.html.erb
<h1> All subs </h1>
<ul>
  <% @subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>
<%= link_to "Create a sub", new_sub_url %>

app/views/subs/new.html.erb
<h1> Spawn a sub </h1>
<%= render "form", action: subs_url, method: "post" %>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<p>
  <%= @sub.description %>
</p>

<h2> Posts: </h2>
<hr>
<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post.url || post_url(post) %> |
      <%= link_to "Comments", post_url(post) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a post", new_post_url %>