config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  resources :subs, except: [:destroy]

  resources :posts, except: [:destroy, :index] do
    member do
      resources :comments, only: [:new]
    end
  end
  resources :comments, only: [:create]

  post "/upvote", to: "votes#upvote"
  post "/downvote", to: "votes#downvote"

  root to: "subs#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title,  use: [:slugged]
  validates :title, :user_id, presence: true

  belongs_to :author,
  foreign_key: :user_id,
  class_name: :User

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub

  has_many :comments

  has_many :votes, as: :votable

  def comments_by_parent_id
    result = Hash.new { [] }
    comments.includes(:author).each do |comment|
      result[comment.parent_comment_id] += [comment]
    end
    result
  end

  def score
    Vote.where(votable_id: id, votable_type: "Post").sum(:value)
  end

  #TODO: order scores 
  # def post_score
  #   .where(votable_type: "Comment")
  #   .group(:votable_id)
  #   .sum(:value)
  # end



  # def self.find
  #   self.friendly.find
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_post_owner, only: [:update, :edit]
  before_action :check_logged_in, only: [:create, :new]



  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @subs = Sub.all
    @post = Post.find_by_slug(params[:id])
    render :edit
  end

  def update
    @post = Post.find_by_slug(params[:id])
    @post.user_id = current_user.id

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.includes(:author, :subs).find_by_slug(params[:id])
    @comment_scores = Comment.where(post_id: @post.id).scores
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  private

  def check_post_owner
    @post = Post.find_by_slug(params[:id])
    unless @post.user_id == current_user.id
      flash[:errors] = ["You cannot edit a post that does not belong to you :("]
      redirect_to post_url(@post)
    end
  end

  def check_logged_in
    unless current_user
      flash[:errors] = ["You must log in before creating a post!"]
      redirect_to new_session_url
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action="<%=action %>", method="post" >
  <input type="hidden" name="_method" value="<%= method %>" />
  <%= auth_token %>

  <label id="post_title"> Title: </label>
    <input
      id="post_title"
      name="post[title]"
      value="<%= @post.title %>"
     />

  <label id="post_url"> URL: </label>
     <input
       id="post_url"
       name="post[url]"
       value="<%= @post.url %>"
      />

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
              value="<%=sub.id %>"
              name="post[sub_ids][]"
              <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      <input type="hidden" name="post[sub_ids][]" value="">
    </label><br>
  <% end %>




  <label id="post_content"> Content </label>
    <textarea
      id="post_content"
      name="post[content]"> <%= @post.content %> </textarea>

  <input type="submit">

</form>

app/views/posts/edit.html.erb
<h1> Modify a post </h1>
<%= render "form", action: post_url(@post), method: "patch" %>

app/views/posts/new.html.erb
<h1> Spawn a post </h1>
<%= render "form", action: posts_url, method: "post" %>

app/views/posts/show.html.erb
<h1> <%= link_to @post.title, @post.url %> </h1>
<p>
  Posted by <%= @post.author.user_name %> at <%= @post.created_at %>
</p>
<%= @post.score %>
<%= render "votes/vote_buttons", votable_id: @post.id, votable_type: "Post" %>
<p>
  <%= @post.content %>
</p>

<h3> Comments: </h3>
<ul>
<% @comments_by_parent_id[nil].each do |comment| %>
  <li> <%= render "comments/comment", comment: comment %> </li>
<% end %>
</ul>

<%= link_to "New comment", new_comment_url(@post) %>  |
<%= link_to "Edit this post", edit_post_url(@post) %>  |
<%= link_to "Back to index", subs_url %>